In [39]:
import pandas as pd
import numpy as np
from IPython.display import display

In [63]:
def sam_analysis():
    print('=======================================')

    print()
    print('사회계정행렬 선택: ')
    print('1. 거시 사회계정행렬 \n 2. 거시 사회계정행렬(국산) \n 3. 미시 사회계정행렬(산업 세분화) \n 4. 미시 사회계정행렬(산업 세분화: 국산) \n 5. 미시 사회계정행렬(최종) \n 6. 미시 사회계정행렬(최종: 국산))')
    print()
    i = int(input('승수 분석을 진행할 SAM의 종류를 선택해주세요. : '))
    
    
    if i == 1:
        data = pd.read_excel('/Users/dongyokim/main/jupyter/2022:Summer/프로젝트/sam 구축/sam_09_1.xlsx', sheet_name='거시 사회계정행렬', skiprows=[0])
        print('데이터 불러오기 완료')
        print('========================================')
        un = 15
    elif i == 2:
        data = pd.read_excel('/Users/dongyokim/main/jupyter/2022:Summer/프로젝트/sam 구축/sam_09_1.xlsx', sheet_name='거시 사회계정행렬 (국산)',skiprows=[0])
        print('데이터 불러오기 완료')
        print('========================================')
        un = 15 
    elif i == 3:
        data = pd.read_excel('/Users/dongyokim/main/jupyter/2022:Summer/프로젝트/sam 구축/sam_09_1.xlsx', sheet_name='미시 사회계정행렬',skiprows=[0])

        un = 35
    elif i == 4:
        data = pd.read_excel('/Users/dongyokim/main/jupyter/2022:Summer/프로젝트/sam 구축/sam_09_1.xlsx', sheet_name='미시 사회계정행렬 (국산)',skiprows=[0])

        un = 35
        
    elif i == 5:
        data = pd.read_excel('/Users/dongyokim/main/jupyter/2022:Summer/프로젝트/sam 구축/sam_09_1.xlsx', sheet_name='미시 사회계정행렬 (최종)',skiprows=[0])

        un = 37
    elif i == 6:
        data = pd.read_excel('/Users/dongyokim/main/jupyter/2022:Summer/프로젝트/sam 구축/sam_09_1.xlsx', sheet_name='미시 사회계정행렬 (최종 국산)',skiprows=[0])

        un = 37
        
    else:
        print('번호를 잘못 입력했습니다. 함수를 다시 실행해주세요. ')
        print('========================================')
        
    data.drop('Unnamed: 0', axis=1, inplace=True)

    
    
    data.rename(columns={'Unnamed: 1':'구분', 'Unnamed: {}'.format(un):'총계'},inplace=True)
    data['구분'] = data['구분'].fillna('총계')
    print()
    data.set_index('구분', inplace=True)
    data.fillna(0, inplace=True)
    data.replace(' ', 0, inplace=True)
    data = data.astype('float')
    
    # 복사용 데이터 
    copy_data = data.copy()
    
    print('데이터 전처리 및 불러오기 완료')
    display(data)
    print('========================================')
    
    
    s11 = data.loc[:'정부', :'정부'].values

    s12 = data.loc[:'정부', '고정자본형성':'수입'].values
    
    s21 = data.loc['고정자본형성':'수입', :'정부'].values
    
    s22 = data.loc['고정자본형성':'수입', '고정자본형성':'수입'].values
    
    
    
    y1_r = data.loc['총계', :'정부'].values.reshape(1, -1)
    
    y2_r = data.loc['총계', '고정자본형성':'수입'].values.reshape(1, -1)
        

    
    y1_c = data.loc[:'정부', '총계'].values.reshape(-1, 1)
    y2_c = data.loc['고정자본형성':'수입', '총계'].values.reshape(-1, 1)
    
    
    # 투입계수 도출 
    
    h11 = s11 / y1_r
    h12 = s12 / y2_r
    h21 = s21 / y1_r
    h22 = s22 / y2_r
    
        
    # 승수행렬
    SAM_multiplier = np.linalg.inv(np.identity(h11.shape[0])-h11)   
    print()
    print('승수 행렬 : ')
    print(SAM_multiplier)
    
    print('어느 항목에 변화를 주겠습니까(번호 선택)? ')
    
    print('외생 변수 선택 : ')
    choise = int(input('1. 고정자본형성 \n 2. SCT 고정자본형성 \n 3. 간접세 \n 4. 법인세 \n 5. 소득세 \n 6. 관세 \n 7. 수출 \n 8. 수입'))

    print('===================================================')
    
    if choise == 1:
        target = '고정자본형성'
    elif choise == 2:
        target = 'SCT 고정자본형성'
    elif choise == 3:
        target = '간접세'
    elif choise == 4:
        target = '법인세'
    elif choise == 5"
        target = '소득세'
    elif choise == 6:
        target = '관세'
    elif choise == 7:
        target = '수출'
    elif choise == 8:
        target = '수입'
        
    

In [61]:
sam_analysis()


사회계정행렬 선택: 
1. 거시 사회계정행렬 
 2. 거시 사회계정행렬(국산) 
 3. 미시 사회계정행렬(산업 세분화) 
 4. 미시 사회계정행렬(산업 세분화: 국산) 
 5. 미시 사회계정행렬(최종) 
 6. 미시 사회계정행렬(최종: 국산))

승수 분석을 진행할 SAM의 종류를 선택해주세요. : 1
데이터 불러오기 완료

데이터 전처리 및 불러오기 완료


중간재화          노동          자본           가계          기업  \
구분                                                                     
중간재화    2465176.361       0.000       0.000   935933.779       0.000   
노동       913408.764       0.000       0.000        0.000       0.000   
자본       826673.012       0.000       0.000        0.000       0.000   
가계            0.000  913408.764  261977.700        0.000       0.000   
기업            0.000       0.000  564695.312        0.000       0.000   
정부            0.000       0.000       0.000        0.000   98638.134   
고정자본형성        0.000       0.000       0.000   143097.000  393882.900   
간접세      160659.128       0.000       0.000        0.000       0.000   
법인세           0.000       0.000       0.000        0.000   72174.278   
소득세           0.000       0.000       0.000    96355.685       0.000   
관세        23757.156       0.000       0.000        0.000       0.000   
수출            0.000       0.000       0.000        0.000       0.000   
수입       707821.334       0.000       0.000        0.000       0.000   
총계      5097495.755  913408.764  826673.012  1175386.464  564695.312   

               정부      고정자본형성         간접세        법인세        소득세         관세  \
구분                                                                           
중간재화    328663.18  606119.428       0.000      0.000      0.000      0.000   
노동           0.00       0.000       0.000      0.000      0.000      0.000   
자본           0.00       0.000       0.000      0.000      0.000      0.000   
가계           0.00       0.000       0.000      0.000      0.000      0.000   
기업           0.00       0.000       0.000      0.000      0.000      0.000   
정부           0.00   10713.599  160659.128  72174.278  96355.685  23757.156   
고정자본형성  133634.80       0.000       0.000      0.000      0.000      0.000   
간접세          0.00       0.000       0.000      0.000      0.000      0.000   
법인세          0.00       0.000       0.000      0.000      0.000      0.000   
소득세          0.00       0.000       0.000      0.000      0.000      0.000   
관세           0.00       0.000       0.000      0.000      0.000      0.000   
수출           0.00       0.000       0.000      0.000      0.000      0.000   
수입           0.00   53781.673       0.000      0.000      0.000      0.000   
총계      462297.98  670614.700  160659.128  72174.278  96355.685  23757.156   

                수출          수입           총계  
구분                                           
중간재화    761603.007       0.000  5097495.755  
노동           0.000       0.000   913408.764  
자본           0.000       0.000   826673.012  
가계           0.000       0.000  1175386.464  
기업           0.000       0.000   564695.312  
정부           0.000       0.000   462297.980  
고정자본형성       0.000       0.000   670614.700  
간접세          0.000       0.000   160659.128  
법인세          0.000       0.000    72174.278  
소득세          0.000       0.000    96355.685  
관세           0.000       0.000    23757.156  
수출           0.000  761603.007   761603.007  
수입           0.000       0.000   761603.007  
총계      761603.007  761603.007        0.000


승수 행렬 : 
[[3.13448916 2.49592315 1.05686622 2.49592315 0.38924809 2.22841375]
 [0.56166204 1.44723884 0.18937747 0.44723884 0.06974849 0.39930443]
 [0.50832756 0.40476979 1.17139451 0.40476979 0.06312529 0.36138716]
 [0.72275414 1.57551285 0.56059951 1.57551285 0.08975328 0.51383022]
 [0.34723547 0.27649579 0.80017247 0.27649579 1.0431205  0.24686137]
 [0.06065334 0.04829689 0.1397701  0.04829689 0.18220704 1.0431205 ]]


In [64]:
data = pd.read_excel('/Users/dongyokim/main/jupyter/2022:Summer/프로젝트/sam 구축/sam_09_1.xlsx',  sheet_name='거시 사회계정행렬',skiprows=[0])

In [65]:
data.drop('Unnamed: 0', axis=1, inplace=True)

In [66]:
data.rename(columns={'Unnamed: 1':'구분', 'Unnamed: 15':'총계'},inplace=True)

In [67]:
data['구분'] = data['구분'].fillna('총계')

In [68]:
data.set_index('구분', inplace=True)

In [69]:
data.fillna(0, inplace=True)
data.replace(' ', 0, inplace=True)

In [70]:
data = data.astype('float')

In [71]:
s11 = data.loc[:'정부', :'정부'].values

In [72]:
s12 = data.loc[:'정부', '고정자본형성':'수입'].values

In [73]:
s21 = data.loc['고정자본형성':'수입', :'정부'].values

In [74]:
s22 = data.loc['고정자본형성':'수입', '고정자본형성':'수입'].values

In [75]:
y1_r = data.loc['총계', :'정부'].values.reshape(1, 6)

In [76]:
y2_r = data.loc['총계', '고정자본형성':'수입'].values.reshape(1, 7)

In [77]:
y1_c = data.loc[:'정부', '총계'].values.reshape(6, 1)
y2_c = data.loc['고정자본형성':'수입', '총계'].values.reshape(7, 1)

In [78]:
h11 = s11 / y1_r
h12 = s12 / y2_r
h21 = s21 / y1_r
h22 = s22 / y2_r

In [79]:
# 승수행렬
SAM_multiplier = np.linalg.inv(np.identity(h11.shape[0])-h11)

In [81]:
result_vector = np.dot(np.dot(SAM_multiplier, h12), y2_r.transpose()).transpose()

In [82]:
update_endogenous_metrix = h11 * result_vector

In [83]:
update_endogenous_metrix

array([[2465176.361,       0.   ,       0.   ,  935933.779,       0.   ,
         328663.18 ],
       [ 913408.764,       0.   ,       0.   ,       0.   ,       0.   ,
              0.   ],
       [ 826673.012,       0.   ,       0.   ,       0.   ,       0.   ,
              0.   ],
       [      0.   ,  913408.764,  261977.7  ,       0.   ,       0.   ,
              0.   ],
       [      0.   ,       0.   ,  564695.312,       0.   ,       0.   ,
              0.   ],
       [      0.   ,       0.   ,       0.   ,       0.   ,   98638.134,
              0.   ]])

In [78]:
update_endogenous_metrix

array([[2465176.361,       0.   ,       0.   ,  935933.779,       0.   ,
         328663.18 ],
       [ 913408.764,       0.   ,       0.   ,       0.   ,       0.   ,
              0.   ],
       [ 826673.012,       0.   ,       0.   ,       0.   ,       0.   ,
              0.   ],
       [      0.   ,  913408.764,  261977.7  ,       0.   ,       0.   ,
              0.   ],
       [      0.   ,       0.   ,  564695.312,       0.   ,       0.   ,
              0.   ],
       [      0.   ,       0.   ,       0.   ,       0.   ,   98638.134,
              0.   ]])